version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive


    echo %PATH%
    
    Set Path=%path%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin

    mingw-get install mingw32-pthreads-w32-dev

    make

    7z.exe a linuxtest.zip protobuf.so p.so
test_script:
# - cmd: skynet.exe autotest\config
artifacts:
- path: linuxtest.zip
  name: linuxtest