version: 1.0.{build}
build_script:
- cmd: >-
    git submodule update --init --recursive

    make

    7z.exe a linuxtest.zip 
test_script:
# - cmd: skynet.exe autotest\config
artifacts:
- path: linuxtest.zip
  name: linuxtest